### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Giszmo** [Kunagi/wartsapp#3]
Demo doesn't load any content for a minute straight.

Probably because of this?
![Screenshot from 2021-03-03 18-42-11](https://user-images.githubusercontent.com/96378/109876757-e5d37300-7c50-11eb-95a5-b0f4d2e8fcdf.png)

**Comment by witek** [comment]
Thank you for the feedback. This was a weekend project during the WirVsVirius Hackathon in 2020. We are not working on it anymore.
